export const MARQUEE_SECTIONS = [
  {
    id: 'moving-animation',
    wrapperId: 'marque-wrapper',
    direction: 'marque-left',
    logoClass: 'logo',
    items: [
      'html',
      'css',
      'javascript',
      'reactjs',
      'nodejs',
      'expressjs',
      'nextjs',
      'typescript',
      'angular',
      'bootstrap',
      'coffeescript',
      'django',
      'git',
      'github',
      'npm',
      'redis',
      'yarn',
    ],
    imagePath: 'web',
  },
  {
    id: 'moving-animation-db-devops',
    wrapperId: 'marque-wrapper-db-devops',
    direction: 'marque-right',
    logoClass: 'logo-db-devops',
    items: [
      'aws',
      'gcp',
      'docker',
      'kubernetes',
      'mongodb',
      'apache',
      'cassandra',
      'graphql',
      'magento',
      'mariadb',
      'mysql',
      'neo4j',
      'oracle',
      'postgresql',
      'redis',
      'sql',
      'sqlserver',
    ],
    imagePath: 'db',
  },
  {
    id: 'moving-animation',
    wrapperId: 'marque-wrapper',
    direction: 'marque-left',
    logoClass: 'logo',
    items: [
      'java',
      'cpp',
      'c',
      'python',
      'go',
      'php',
      'rust',
      'swift',
      'ruby',
      'kotlin',
      'javascript',
      'perl',
      'r',
      'csharp',
      'typescript',
      'dart',
      'go2',
    ],
    imagePath: 'prog',
  },
];
