export const languages = [
  {
    category: 'Working',
    items: ['Java', 'C', 'Python', 'Cpp', 'JavaScript', 'PHP', 'Rust', 'R', 'SQL'],
  },
  {
    category: 'POPULAR',
    items: [
      'C',
      'Python',
      'Cpp',
      'Java',
      'MySQL',
      'HTML',
      'JavaScript',
      'TypeScript',
      'Perl',
      'Fortran',
      'PHP',
      'SQL',
      'NodeJS',
      'MongoDB',
      'Kotlin',
      'Ruby',
      'Rust',
      'Swift',
      'Bash',
      'Redis',
    ],
  },
  {
    category: 'PROGRAMMING',
    items: [
      'Java',
      'Python',
      'C',
      'Cpp',
      'Go',
      'Rust',
      'PHP',
      'JavaScript',
      'NodeJS',
      'Scala',
      'Ruby',
      'R',
      'Kotlin',
      'Pascal',
      'Cobol',
      'Lua',
      'Fortran',
      'Assembly',
      'Groovy',
      'Bash',
      'Clojure',
      'Perl',
      'C#',
      'TypeScript',
      'Prolog',
      'Swift',
      'Objective-C',
      'CoffeeScript',
      'EJS',
    ],
  },
  {
    category: 'WEB',
    items: [
      'HTML',
      'CSS',
      'JavaScript',
      'JSON',
      'XML',
      'Angular',
      'Vue',
      'yaml',
      'markdown',
      'Vue3',
      'Materialize',
      'Bootstrap',
      'JQuery',
      'Foundation',
      'Bulma',
      'Uikit',
      'Semantic UI',
      'Skeleton',
      'Milligram',
      'React',
      'BackboneJS',
    ],
  },
  {
    category: 'DATABASES',
    items: [
      'MySQL',
      'Oracle',
      'PostgreSQL',
      'SQL',
      'MongoDB',
      'SQLite',
      'Redis',
      'MariaDB',
      'SQLServer',
    ],
  },
];
